parameters:
  - name: enabled
    type: boolean
    default: true
  - name: serviceConnection
    type: string
    default: false
  - name: workingDirectory
    type: string
    default: $(Pipeline.Workspace)/s

steps:
  - task: AzureCLI@2
    enabled: ${{ parameters.enabled }}
    displayName: Helm upgrade
    env:
      KUBECONFIG: "$(Pipeline.Workspace)/kubeconfig"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      workingDirectory: ${{ parameters.workingDirectory }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -x
        ls -l 
        pwd
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install public-ingress-nginx ingress-nginx/ingress-nginx \
        --namespace public-ingress \
        --create-namespace \
        --set controller.replicaCount=1 \
        --set controller.ingressClassResource.controllerValue=k8s.io/public-ingress-nginx \
        --set controller.ingressClass=public-ingress \
        --set controller.ingressClassResource.name=public-ingress \
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
        --set controller.allowSnippetAnnotations=true
