parameters:
  - name: agentPool
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []
  - name: legacyPeerDeps
    type: boolean
    default: false
  - name: packageDirectory
    type: string
  - name: artifactFeedName
    type: string
  - name: buildPackageName
    type: string
  - name: packagePublishDescription
    type: string
  - name: versionOption
    type: string    

jobs:
  - job: PullRequestEvent
    displayName: Pull Request Event
    pool: ${{ parameters.agentPool }}
    steps:
      - ${{ parameters.repoCheckoutSteps }}

      - template: ../../common/steps/launch_make_configure.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
      
      - template: ../steps/npm_install.yaml
        parameters:
          legacyPeerDeps: ${{ parameters.legacyPeerDeps }}

      - template: ../steps/npm_build.yaml

      - template: ../steps/npm_public_build_artifact.yaml
        parameters:
          packageDirectory: ${{ parameters.packageDirectory }}   
          artifactFeedName: ${{ parameters.artifactFeedName }}
          buildPackageName: ${{ parameters.buildPackageName }}
          packagePublishDescription: ${{ parameters.packagePublishDescription }}
          versionOption: ${{ parameters.versionOption }}
