parameters:
  - name: agentPool
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []
  - name: legacyPeerDeps
    type: boolean
    default: false

jobs:
  - job: PullRequestEvent
    displayName: Pull Request Event
    pool: ${{ parameters.agentPool }}
    steps:
      - ${{ parameters.repoCheckoutSteps }}

      - template: ../../common/steps/launch_make_configure.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
      
      - template: ../steps/npm_install.yml
        parameters:
          legacyPeerDeps: ${{ parameters.legacyPeerDeps }}
