parameters:
  - name: vmImageNameAKSHosted
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []

jobs:
  - job: PullRequestEvent
    displayName: Pull Request Event
    pool:
      vmImage: ${{ parameters.vmImageNameAKSHosted }}
    steps:
      - ${{ parameters.repoCheckoutSteps }}

      - template: ../steps/launch_make_configure.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
