parameters:
  - name: agentPool
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []
  - name: legacyPeerDeps
    type: boolean
    default: false
  - name: packageDirectory
    type: string
  - name: artifactFeedName
    type: string
  - name: buildPackageName
    type: string
  - name: packagePublishDescription
    type: string
  - name: versionOption
    type: string    

stages:
  - stage: BuildAngularApplication
    displayName: 'Build Angular Application'
    jobs:
      - template: ../jobs/build.yaml
        parameters:
          agentPool: ${{ parameters.agentPool }}
          serviceConnection: ${{ parameters.serviceConnection }}
          repoCheckoutSteps: ${{ parameters.repoCheckoutSteps }}
          legacyPeerDeps: ${{ parameters.legacyPeerDeps }}
          packageDirectory: ${{ parameters.packageDirectory }}
          artifactFeedName: ${{ parameters.artifactFeedName }}
          buildPackageName: ${{ parameters.buildPackageName }}
          packagePublishDescription: ${{ parameters.packagePublishDescription }}
          versionOption: ${{ parameters.versionOption }}
