parameters:
  - name: agentPool
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []
  - name: artifactFeedName
    type: string
  - name: buildPackageName
    type: string
  - name: packageVersion
    type: string    
  - name: downloadDirectory
    type: string   
  - name: srcAppConfigJsonPath
    type: string
  - name: destAppConfigJsonDirPath
    type: string 
  - name: storageAccountName
    type: string
  - name: srcFilePath
    type: string     
  - name: timeInMinutes
    type: number
    default: 1       

stages:
  - ${{ each deployEnv in parameters.deployEnvironments }}:
    - stage: ${{ deployEnv.environment}}_PreDeploy
      displayName: '${{ deployEnv.environment }} - Pre deploy'
      dependsOn: ${{ deployEnv.dependsOn }}
      jobs:
        - template: ../jobs/deploy.yaml
          parameters:
            agentPool: ${{ deployEnv.agentPool }}
            serviceConnection: ${{ deployEnv.serviceConnection }}
            repoCheckoutSteps: ${{ deployEnv.repoCheckoutSteps }}
            artifactFeedName: ${{ deployEnv.artifactFeedName }}
            buildPackageName: ${{ deployEnv.buildPackageName }}
            packageVersion: ${{ deployEnv.packageVersion }}
            downloadDirectory: ${{ deployEnv.downloadDirectory }}
            srcAppConfigJsonPath: ${{ deployEnv.srcAppConfigJsonPath }}
            destAppConfigJsonDirPath: ${{ deployEnv.destAppConfigJsonDirPath }}
            storageAccountName: ${{ deployEnv.storageAccountName }}
            srcFilePath: ${{ deployEnv.srcFilePath }}
            timeInMinutes: ${{ deployEnv.timeInMinutes }}
            deploymentEnv: ${{ deployEnv.environment }}
