parameters:
  - name: agentPool
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []
  - name: artifactFeedName
    type: string
  - name: buildPackageName
    type: string
  - name: packageVersion
    type: string    
  - name: downloadDirectory
    type: string   
  - name: srcAppConfigJsonPath
    type: string
  - name: destAppConfigJsonDirPath
    type: string 
  - name: storageAccountName
    type: string
  - name: srcFilePath
    type: string     
  - name: timeInMinutes
    type: number
    default: 1       

stages:
  - stage: DeployAngularApplication
    displayName: 'Deploy Angular Application'
    jobs:
      - template: ../jobs/deploy.yaml
        parameters:
          agentPool: ${{ parameters.agentPool }}
          serviceConnection: ${{ parameters.serviceConnection }}
          repoCheckoutSteps: ${{ parameters.repoCheckoutSteps }}
          artifactFeedName: ${{ parameters.artifactFeedName }}
          buildPackageName: ${{ parameters.buildPackageName }}
          packageVersion: ${{ parameters.packageVersion }}
          downloadDirectory: ${{ parameters.downloadDirectory }}
          srcAppConfigJsonPath: ${{ parameters.srcAppConfigJsonPath }}
          destAppConfigJsonDirPath: ${{ parameters.destAppConfigJsonDirPath }}
          storageAccountName: ${{ parameters.storageAccountName }}
          srcFilePath: ${{ parameters.srcFilePath }}
          timeInMinutes: ${{ parameters.timeInMinutes }}
