parameters:
- name: deployEnvironments
  type: object
  default: []
- name: agentPool
  type: string
  default: ''

stages:
  - ${{ each deployEnv in parameters.deployEnvironments }}:
    # - stage: ${{ deployEnv.environment}}_Ingress_PreDeploy
    #   displayName: '${{ deployEnv.environment }} - Ingress Pre deploy'
    #   dependsOn: ${{deployEnv.dependsOn}}
    #   ${{ if deployEnv.variableFile }}:
    #     variables:
    #       - template: ${{ deployEnv.variableFile }}@self
    #   jobs:
    #     - template: ../jobs/generic-job.yaml
    #       parameters:
    #         jobName: ${{ deployEnv.environment }}_Ingress_PreDeployJob
    #         jobDisplayName: '${{ deployEnv.environment }} - Ingress Pre deploy'
    #         poolName: ${{ parameters.agentPool }}
    #         workspace:
    #           clean: all
    #         steps:
    #           - template: ../steps/asdf-install.yaml
    #             parameters:
    #               pluginName: 'helm-diff'
    #               pluginVersion: '3.9.5'
    #           - template: ../steps/get-kubernetes-credentials.yaml
    #             parameters:
    #               serviceConnection: ${{ deployEnv.serviceConnection }}
    #               aksResourceGroup: $(aksResourceGroup)
    #               aksCluster: $(aksCluster)
    - stage: ${{ deployEnv.environment }}_Ingress_Deploy
      displayName: '${{ deployEnv.environment }} - Ingress Deploy'
      dependsOn: ${{ deployEnv.environment}}_Ingress_PreDeploy
      ${{ if deployEnv.variableFile }}:
        variables:
          - template: ${{ deployEnv.variableFile }}@self
      jobs:
        - template: ../jobs/deploy-job.yaml
          parameters:
            jobName: ${{ deployEnv.environment }}_Ingress_DeployJob
            jobDisplayName: '${{ deployEnv.environment }} - Ingress Deploy'
            poolName: ${{ parameters.agentPool }}
            workspace:
              clean: all
            azureEnvironment: ${{ deployEnv.azureEnvironment }}
            steps:
              - template: ../steps/verify-ado-agent.yaml
              - template: ../steps/get-kubernetes-credentials.yaml
                parameters:
                  serviceConnection: ${{ deployEnv.serviceConnection }}
                  aksResourceGroup: $(aksResourceGroup)
                  aksCluster: $(aksCluster)
              - template: ../steps/helm-install-ingress.yaml
                parameters:
                  serviceConnection: ${{ deployEnv.serviceConnection }}
                  releaseName: $(helmReleaseName)
                  ingressClass: $(ingressClass)
                  namespace: $(namespace)
                  helmRepoName: $(helmRepoName)
                  helmRepoUrl: $(helmRepoUrl)
                  helmChartReference: $(helmChartReference)