# This pipeline template assumes that a variableFile must be passed as parameter to the template in the `deployEnv` object

parameters:
- name: deployEnvironments
  type: object
  default: []
  # Sample deployEnvironments object
  # - environment: sandbox
  #   region: eastus
  #   environmentNumber: "000"
  #   azureEnvironment: az-env-000
  #   serviceConnection: $(service_connection_sandbox)
- name: agentPool
  type: string
  default: ''

stages:
  - ${{ each deployEnv in parameters.deployEnvironments }}:
    - stage: ${{ deployEnv.environment}}_PreDeploy
      displayName: '${{ deployEnv.environment }} - Pre deploy'
      dependsOn: ${{deployEnv.dependsOn}}
      ${{ if deployEnv.variableFile }}:
        variables:
          - template: ${{ deployEnv.variableFile }}
      jobs:
        - job: PreDeployDevJob
          displayName: '${{ deployEnv.environment }} - Pre deploy'
          pool: ${{ parameters.agentPool }}
          workspace:
            clean: all
          steps:
            - template: ../steps/asdf-install.yaml
              parameters:
                pluginName: 'helm-diff'
                pluginVersion: '3.9.5'
            - template: ../steps/get-kubernetes-credentials.yaml
              parameters:
                serviceConnection: ${{ variables.serviceConnection }}
                aksResourceGroup: $(aksResourceGroup)
                aksCluster: $(aksCluster)
            - template: ../steps/helm-acr-login.yaml
              parameters:
                serviceConnection: ${{ variables.serviceConnection }}
                acrName: ${{ deployEnv.acrName }}
            - template: ../steps/helm-diff.yaml
              parameters:
                serviceConnection: ${{ variables.serviceConnection }}
                namespace: $(namespace)
                releaseName: $(releaseName)
                acrName: ${{ deployEnv.acrName }}
                imageName: ${{ deployEnv.imageName }}
                imageTag: ${{ deployEnv.imageTag }}
                deployEnv: ${{ deployEnv.environment }}
                helmChart: $(helmChart)
                helmChartVersion: $(helmChartVersion)
                  
    - stage: ${{ deployEnv.environment }}_Deploy
      displayName: '${{ deployEnv.environment }} - Deploy'
      dependsOn: ${{ deployEnv.environment}}_PreDeploy
      ${{ if deployEnv.variableFile }}:
        variables:
          - template: ${{ deployEnv.variableFile }}
      jobs:
        - deployment: ${{ deployEnv.environment }}_DeployJob
          displayName: '${{ deployEnv.environment }} Deploy'
          pool: ${{ parameters.agentPool }}
          workspace:
            clean: all
          environment: ${{ variables.azureEnvironment }}
          strategy:
            runOnce:
              deploy:
                steps:
                  # Explicit checkout is needed in deploy job
                  - template: ../steps/verify-ado-agent.yaml
                  - template: ../steps/get-kubernetes-credentials.yaml
                    parameters:
                      serviceConnection: ${{ variables.serviceConnection }}
                      aksResourceGroup: $(aksResourceGroup)
                      aksCluster: $(aksCluster)
                  - template: ../steps/helm-acr-login.yaml
                    parameters:
                      serviceConnection: ${{ variables.serviceConnection }}
                      acrName: ${{ deployEnv.acrName }}
                  - checkout: self
                  - template: ../steps/helm-upgrade.yaml
                    parameters:
                      serviceConnection: ${{ variables.serviceConnection }}
                      namespace: $(namespace)
                      releaseName: $(helmReleaseName)
                      acrName: ${{ deployEnv.acrName }}
                      imageName: ${{ deployEnv.imageName }}
                      imageTag: ${{ deployEnv.imageTag }}
                      deployEnv: ${{ deployEnv.environment }}
                      helmChart: $(helmChart)
                      helmChartVersion: $(helmChartVersion)
                        
