parameters:
  - name: vmImageNameMSFTHosted
    type: string

stages:
  - stage: Sandbox
    jobs:
      - template: ../jobs/deploy.yaml
        parameters:
          vmImageNameMSFTHosted: ${{ parameters.vmImageNameMSFTHosted }}
