parameters:
- name: environments
  type: object
  default: []

- name: common
  type: object
  default: []

stages:
- template: ./steps/launch_init_remote_state.yml

- template: ./steps/launch_terraform_plan.yml


# - ${{ each env in parameters.environments }}:
#   - template: ./terragrunt/stages/approval.yml
#     parameters: 
#       approval: ${{ env.approval }}

#   - ${{ if ne(env.infraValidation.jobData.configjsonschemapath, '') }}:
#     - template: ./pipeline/stages/infra_jsonvalidation.yml
#       parameters:
#         common: ${{ parameters.common }}
#         infraValidation: ${{ env.infraValidation }}      

#   - template: ./terragrunt/stages/remote_backend.yml
#     parameters: 
#       armServiceConnection: ${{ env.armServiceConnection }}
#       azureSubscriptionId: ${{ env.azureSubscriptionId }}
#       remoteBackend: ${{ env.remoteBackend }}

#   - template: ./terragrunt/stages/${{ parameters.common.tgAppTemplateName}}.yml
#     parameters: 
#       armServiceConnection: ${{ env.armServiceConnection }}
#       azureSubscriptionId: ${{ env.azureSubscriptionId }}
#       appInfra: ${{ env.app_infra }}
        