parameters:
- name: environments
  type: object
  default: []

- name: common
  type: object
  default: []

stages:
# - template: ../steps/launch_init_remote_state.yaml
- template: ../steps/launch_terraform_plan.yaml
