parameters:
- name: environments
  type: object
  default: []

- name: common
  type: object
  default: []

- name: buildInfo
  type: object
  default: []

- name: publishInfo
  type: object
  default: []

stages:
  - ${{ if eq(parameters.common.runBuild, true) }}:
    - ${{ if eq(parameters.common.multiBuild, true) }}:
      - template: /templates/pipeline/stages/multi_build.yml
        parameters:
          common: ${{ parameters.common }}
          buildInfo: ${{ parameters.buildInfo }}
          publishInfo: ${{ parameters.publishInfo }}
    - ${{ else }}:
      - template: /templates/pipeline/stages/${{ parameters.common.runtime }}_build.yml
        parameters:
          common: ${{ parameters.common }}
          buildInfo: ${{ parameters.buildInfo }}
          publishInfo: ${{ parameters.publishInfo }}

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - ${{ each env in parameters.environments }}:
      - template: /templates/terragrunt/stages/approval.yml
        parameters: 
          approval: ${{ env.approval }} 

      - ${{ if eq(parameters.common.runInfra, true) }}:
        - template: /templates/pipeline/stages/infra.yml
          parameters: 
            env: ${{ env }}
            common: ${{ parameters.common }} 
            buildInfo: ${{ parameters.buildInfo }}

      - ${{ if eq(parameters.common.runDeploy, true) }}:
        - template: /templates/pipeline/stages/deploy.yml
          parameters: 
            env: ${{ env }}
            common: ${{ parameters.common }} 
            buildInfo: ${{ parameters.buildInfo }}
            publishInfo: ${{ parameters.publishInfo }}
