# This template will ensure that a CD pipeline run is conducted against a
# tagged version only. This prevents end-users from explicitly running the
# CD pipeline against a branch or commit hash, ensuring that we are only
# deploying tagged artifacts into our cloud environments.

# The current ref is determined from the Build.SourceBranch variable provided
# by Azure DevOps, no other variables need to be present in scope for this
# step.

# parameters:
#  - serviceConnection: the ADO service connection to use to login to
#    the container registry

parameters:
  - name: serviceConnection
    type: string

stages:
  - stage: BuildTagValidation
    displayName: Build Tag Validation
    jobs:
      - template: /common/jobs/generic-job.yaml
        parameters:
          jobName: BuildTagValidation
          jobDisplayName: Build Tag Validation
          poolName: $(agentPool)
          steps:
            - task: AzureClI@2
              name: BuildTagValidation
              displayName: Ensure Build is for a Tag
              inputs:
                scriptType: bash
                scriptLocation: inlineScript
                workingDirectory: $(System.DefaultWorkingDirectory)
                inlineScript: |
                  export PATH=/home/launch/env/bin:$PATH
                  TAGGED=$(echo $SOURCE_BRANCH | grep -P "^refs/tags/")
                  [[ -n $TAGGED ]] || (echo "##vso[task.logissue type=error]CD pipeline can only be run against a tag, not a branch or commit." ; exit 1)
                azureSubscription: ${{ parameters.serviceConnection }
                addSpnToEnvironment: true
              env:
                SOURCE_BRANCH: $(Build.SourceBranch)
