parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: serviceConnection
    type: string
  - name: targetEnvironment
    type: string

stages:
  - stage: PullRequestMerged
    displayName: Pull Request Merged
    jobs:
      - template: ../jobs/generic-job.yaml
        parameters:
          steps:
            - template: ../steps/get_latest_semver_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
