# This template will increment the version tag associated with this repository.
# In order for this stage template to execute, the following conditions must be
# met:
#   - The pipeline is being run against the `refs/heads/main` branch of the
#     repository, and,
#   - The build run must not have been manually triggered by an end user

# First, this template will evaluate whether or not tags in this repository
# match the pattern expected for Semantic Versions. Based on the tags within
# the repository, one of two outcomes is possible:
#
#   - If a semantic tag exists, a new semantic version tag will be created
#     according to the branch name of the previously-merged pull request.
#     See the template at /common/steps/create_semver_tag.yaml for more detail.
#   - If no semantic tag exists, a new tag with the current Build ID will be
#     created and pushed to the repo.
#
# The following variables must be present in the current scope for this job to
# run:
# - agentPool: The name of the ADO Agent pool to run the job on.
# - serviceConnection: The name of the Service Connection to utilize
# - buildSourceBranch: The branch of the triggering repo the build was queued for.
# - pullRequestTargetBranch: The name of the target branch for a pull request.
# - buildId: The ID associated with the current build

parameters:
  - name: serviceConnection
    type: string
  - name: poolName
    type: string

stages:
  - stage: AutomatedVersionUpdate
    displayName: Automated Version Update
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'Manual'))
    jobs:
      - template: /common/jobs/generic-job.yaml
        parameters:
          jobName: AutomatedVersionUpdate
          jobDisplayName: Automated Version Update
          poolName: ${{ parameters.poolName }}
          variables:
            - name: buildSourceBranch
              value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
          steps:
            - template: /common/steps/has_semver_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                outputVariableName: HasSemverTag
            - template: /common/steps/create_semver_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
            - template: /common/steps/create_buildid_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
