# This stage template will validate the branch name meets our requirements for
# automated versioning if semantic versioning is being used in this repo.
# This stage requires no variables to be explicitly set, but needs the
# following parameters:
# - serviceConnection: The name of the Service Connection to utilize
# - poolName: The name of the ADO Agent pool to run the job on.
# - buildSourceBranch: The branch of the triggering repo the build was queued for.
# - pullRequestSourceBranch: The branch that is being reviewed in a pull request.

parameters:
  - name: serviceConnection
    type: string
  - name: poolName
    type: string
  - name: buildSourceBranch
    type: string
  - name: pullRequestSourceBranch
    type: string

stages:
  - stage: BranchNameValidation
    displayName: Branch Name Validation
    condition: "eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')"
    jobs:
      - template: /common/jobs/generic-job.yaml
        parameters:
          jobName: PlatformValidation
          jobDisplayName: Platform Validation
          poolName: ${{ parameters.poolName }}
          steps:
            - template: /common/steps/has_semver_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                outputVariableName: HasSemverTag
            - template: /common/steps/launch_validate_branch_name.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                buildSourceBranch: ${{ parameters.buildSourceBranch }}
                pullRequestSourceBranch: ${{ parameters.pullRequestSourceBranch }}
