# This template will validate the branch name meets our requirements for automated versioning.
# The following variables must be present in the current scope for this job to run:
#  poolName: The name of the ADO Agent pool to run the job on.
#  serviceConnection: The name of the Service Connection to utilize
#  buildSourceBranch: The branch of the triggering repo the build was queued for.
#  pullRequestTargetBranch: The name of the target branch for a pull request.

parameters:
  - name: poolName
    type: string
  - name: serviceConnection
    type: string
  - name: buildSourceBranch
    type: string
  - name: pullRequestSourceBranch
    type: string
  - name: pullRequestTargetBranch
    type: string

stages:
  - stage: BranchNameValidation
    displayName: Branch Name Validation
    jobs:
      - template: /common/jobs/generic-job.yaml
        parameters:
          jobName: PlatformValidation
          jobDisplayName: Platform Validation
          poolName: ${{ parameters.poolName }}
          steps:
            - template: /common/steps/has_semver_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
            - template: /common/steps/launch_validate_branch_name.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                buildSourceBranch: ${{ parameters.buildSourceBranch }}
                pullRequestSourceBranch: ${{ parameters.pullRequestSourceBranch }}
                pullRequestTargetBranch: ${{ parameters.pullRequestTargetBranch }}
                repositoryHasSemverTag: $(HasSemverTag)
