parameters:
  - name: vmImageNameAKSHosted
    type: string
  - name: serviceConnection
    type: string
  - name: repoCheckoutSteps
    type: stepList
    default: []

stages:
  - stage: PullRequestEvent
    displayName: Pull Request Event
    jobs:
      - template: ../jobs/pr_event.yaml
        parameters:
          vmImageNameAKSHosted: ${{ parameters.vmImageNameAKSHosted }}
          serviceConnection: ${{ parameters.serviceConnection }}
          repoCheckoutSteps: ${{ parameters.repoCheckoutSteps }}
