parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: serviceConnection
    type: string
  - name: targetEnvironment
    type: string

stages:
  - stage: PullRequestMerged
    displayName: Pull Request Merged
    jobs:
      - template: ../jobs/pr_merge.yaml
        parameters:
          vmImageNameMSFTHosted: ${{ parameters.vmImageNameMSFTHosted }}
          serviceConnection: ${{ parameters.serviceConnection }}
