parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: serviceConnection
    type: string
  - name: targetEnvironment
    type: string

jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ${{ parameters.vmImageNameMSFTHosted }}
    steps:
      - template: /iac/steps/launch_terragrunt_apply.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          targetEnvironment: ${{ parameters.targetEnvironment }}
