parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: serviceConnection
    type: string
  - name: targetEnvironment
    type: string

jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ${{ parameters.vmImageNameMSFTHosted }}
    steps:
      - template: ../steps/launch-terragrunt-apply.yaml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          targetEnvironment: ${{ parameters.targetEnvironment }}
      - template: ../steps/integration-tests.yaml
        parameters:
          targetEnvironment: ${{ parameters.targetEnvironment }}
