parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: subscriptionId
    type: string

jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ${{ parameters.vmImageNameMSFTHosted }}
    steps:
      - template: ../steps/launch_terragrunt_apply.yaml
        parameters:
          subscriptionId: ${{ parameters.subscriptionId }}
