# This template will build a docker image and push it to the container registry.

# parameters:
#  - name: poolName - The name of the agent pool to run the job on.
#  - name: dockerfile - The path to the Dockerfile. Default is 'Dockerfile'
#  - name: imageRepository - The FQDN of the image repository
#  - name: distPath - the directory containing the build artifacts. Default is 'dist/'
#  - name: serviceConnection - the ADO service connection to use to login to the container registroy
#  - name: dockerImageName - the name of the docker image. Default is the name of the repository

parameters:
  - name: poolName
    type: string
  - name: dockerfile
    type: string
    default: 'Dockerfile'
  - name: imageRepository
    type: string
  - name: distPath
    type: string
    default: 'dist/'
  - name: serviceConnection
    type: string
  - name: dockerImageName
    type: string
    default: ''
  - name: push
    type: boolean
    default: true
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: build_image
    displayName: Build Image
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      - template: /common/jobs/generic-job.yaml
        parameters:
          jobName: BuildImage
          jobDisplayName: Build Image
          poolName: ${{ parameters.poolName }}
          workspace:
            clean: all
          steps:
            - template: /common/steps/get_latest_tag.yaml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                outputVariableName: LatestTag
            - template: /applications/steps/local-build-and-push-docker-image.yaml
              parameters:
                acrRegistry: ${{ parameters.imageRepository }}
                distPath: ${{ parameters.distPath }}
                dockerfile: ${{ parameters.dockerfile }}
                serviceConnection: ${{ parameters.serviceConnection }}
                push: ${{ parameters.push }}
                ${{ if ne(parameters.dockerImageName, '') }}:
                  dockerImageName: ${{ parameters.dockerImageName }}
                ${{ else }}:
                  dockerImageName: $(Build.Repository.Name)
                dockerImageTag: |
                  $(LatestTag)
                  latest
