# This template is a multistage template to deploy oauth2-proxy on AKS cluster

# This pipeline template assumes that a variableFile must be passed as parameter to the template in the `deployEnv` object
# Expect the following variables to be available in the variable file
# variables: 
#   - name: serviceConnection
#     value: 'trp_dev'
#   - name: agentPool
#     value: 'dev-k8s-pool'
#   - name: aksCluster
#     value: 'trp-appsk8s-dev-000-aks'
#   - name: aksResourceGroup
#     value: 'trp-appsk8s-govva-dev-000-rg-000'
#   - name: helmChart
#     value: 'oauth2-proxy'
#   - name: helmChartRepoUrl
#     value: 'https://oauth2-proxy.github.io/manifests'
#   - name: helmChartVersion
#     value: '7.7.8'
#   - name: helmReleaseName
#     value: 'sample-oauth2-proxy'
#   - name: namespace
#     value: 'dev'
#   - name: azureEnvironment
#     value: 'aks-sample-oauth2-dev'
#   - name: deployEnvironment
#     value: 'dev'
#   - name: keyVaultName
#     value: 'trp-dev-vault'
#   - name: runAsPreJob
#     value: true
#   # The below secret mappings must exist in the variables file. The key must always be the same. The value refers to the secret name in key vault
#   - name: OAUTH2_ADFS_CLIENT_ID
#     value: 'dslu-oauth2-adfs-client-id'
#   - name: OAUTH2_ADFS_CLIENT_SECRET
#     value: 'dslu-oauth2-adfs-client-secret'
#   - name: OAUTH2_COOKIE_SECRET
#     value: 'dslu-oauth2-cookie-secret'


parameters:
- name: deployEnvironments
  type: object
  default: []
  # Sample deployEnvironments object
  # environment: 'test'
  # dependsOn: 'dev_Deploy' # Must be empty for the first stage
  # variableFile: '/envs/test/pipelines/variables.yaml@self'
  # aksAdEnabled: false
  # overrideValuesFile: 'envs/dev/oauth2/values.yaml'

stages:
  - ${{ each deployEnv in parameters.deployEnvironments }}:
    - stage: ${{ deployEnv.environment}}_PreDeploy
      displayName: '${{ deployEnv.environment }} - Pre deploy'
      dependsOn: ${{deployEnv.dependsOn}}
      # Most of the variables used later in the file to pass values to parameters come from this variable file
      ${{ if deployEnv.variableFile }}:
        variables:
          - template: ${{ deployEnv.variableFile }}
      jobs:
        - template: ../../common/jobs/generic-job.yaml
          parameters:
            jobName: ${{ deployEnv.environment }}_PreDeployJob
            jobDisplayName: '${{ deployEnv.environment }} - Pre deploy'
            # Agent pool would be different for each environment. Comes from envs/{env}/pipelines/variables.yaml
            poolName: ${{ variables.agentPool }}
            workspace:
              clean: all
            steps:
              - template: ../steps/get-kubernetes-credentials.yaml
                parameters:
                  serviceConnection: ${{ variables.serviceConnection }}
                  aksResourceGroup: ${{ variables.aksResourceGroup }}
                  aksCluster: ${{ variables.aksCluster }}
                  aksAdEnabled: ${{ deployEnv.aksAdEnabled }}
              - template: ../steps/oauth2-proxy-helm-diff.yaml
                parameters:
                  serviceConnection: ${{ variables.serviceConnection }}
                  namespace: ${{ variables.namespace }}
                  releaseName: ${{ variables.helmReleaseName }}
                  deployEnv: ${{ variables.deployEnvironment }}
                  helmChart: ${{ variables.helmChart }}
                  helmChartVersion: ${{ variables.helmChartVersion }}
                  helmChartRepoUrl: ${{ variables.helmChartRepoUrl }}
                  overrideValuesFile: ${{ deployEnv.overrideValuesFile }}
    - stage: ${{ deployEnv.environment }}_Deploy
      displayName: '${{ deployEnv.environment }} - Deploy'
      dependsOn: ${{ deployEnv.environment}}_PreDeploy
      ${{ if deployEnv.variableFile }}:
        variables:
          - template: ${{ deployEnv.variableFile }}
      jobs:
        - template: ../../common/jobs/deploy-job.yaml
          parameters:
            jobName: ${{ deployEnv.environment }}_DeployJob
            jobDisplayName: '${{ deployEnv.environment }} - Deploy'
             # Agent pool would be different for each environment. Comes from envs/{env}/pipelines/variables.yaml
            poolName: ${{ variables.agentPool }}
            workspace:
              clean: all
            azureEnvironment: ${{ variables.azureEnvironment }}
            steps:
              - template: ../../common/steps/verify-ado-agent.yaml
              - template: ../steps/get-kubernetes-credentials.yaml
                parameters:
                  serviceConnection: ${{ variables.serviceConnection }}
                  aksResourceGroup: ${{ variables.aksResourceGroup }}
                  aksCluster: ${{ variables.aksCluster }}
                  aksAdEnabled: ${{ deployEnv.aksAdEnabled }}
              #- checkout: self
              - template: ../steps/oauth2-proxy-helm-upgrade.yaml
                parameters:
                  serviceConnection: ${{ variables.serviceConnection }}
                  namespace: ${{ variables.namespace }}
                  releaseName: ${{ variables.helmReleaseName }}
                  deployEnv: ${{ variables.deployEnvironment }}
                  helmChart: ${{ variables.helmChart }}
                  helmChartVersion: ${{ variables.helmChartVersion }}
                  helmChartRepoUrl: ${{ variables.helmChartRepoUrl }}
                  overrideValuesFile: ${{ deployEnv.overrideValuesFile }}
        
                        
