parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: serviceConnection
    type: string

stages:
  - template: ../stages/sandbox.yaml
    parameters:
      vmImageNameMSFTHosted: ${{ parameters.vmImageNameMSFTHosted }}
      serviceConnection: ${{ parameters.serviceConnection }}
