parameters:
  - name: vmImageNameMSFTHosted
    type: string
  - name: subscriptionId
    type: string

stages:
  - template: ../stages/sandbox.yaml
    parameters:
      vmImageNameMSFTHosted: ${{ parameters.vmImageNameMSFTHosted }}
      subscriptionId: ${{ parameters.subscriptionId }}
